import Head from 'next/head'

import { Header } from '@/components/sections/Header'
import { Hero } from '@/components/sections/Hero'
import { Media } from '@/components/sections/Media'

export default function Landing() {
  return (
    <>
      <Head>
        <title>Leadster - O futuro da geração de leads</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Media />
    </>
  )
}
